import type { Metadata } from 'next'
import './globals.css'
export const metadata: Metadata = {
    title: 'HOTTAKE',
    description: 'Generated by hono'
}

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
      <html lang="en">
          <body className="w-screen h-screen bg-stone-100 p-0 m-0 overflow-hidden">
            {children}
            </body>
      </html>
    )
}
