import type { Metadata } from 'next'
import './globals.css'
import "@radix-ui/themes/styles.css";
import { EuropaRegular } from './lib/loadFont'
import { Theme } from "@radix-ui/themes";

export const metadata: Metadata = {
    title: 'HOTTAKE',
    description: 'Generated by hono'
}

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
      <html lang="en">
            <body className={`w-screen ${EuropaRegular.className} tracking-wider h-full bg-[#0c0c0e] text-sm p-0 m-0 overflow-hidden`}>
                <Theme accentColor='red'>
                    {children}
                </Theme>
            </body>
      </html>
    )
}
